### ISSUE TITLE
Cannot find module 'ngx-permissions' from 

### ISSUE THREAD

**Issue by suspecie** [AlexKhymenko/ngx-permissions#208]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
I'm trying to do an unit test using jest + angular.
But when I run unit test, test fail because ngx-permissions package it not reconigzed.

<pre> 
 FAIL  src/app/core/components/permissions/permissions.service.spec.ts
  ● Test suite failed to run

    Cannot find module 'ngx-permissions' from 'src/app/core/components/permissions/permissions.service.spec.ts'

      1 | import { TestBed } from '@angular/core/testing';
    > 2 | import { NgxPermissionsService } from 'ngx-permissions';
        | ^
      3 |
      4 | import { PermissionsService } from './permissions.service';
      5 |

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (src/app/core/components/permissions/permissions.service.spec.ts:2:1)
</pre>

## Expected behavior
Created Unit Test with Jest + Angular

## Minimal reproduction of the problem with instructions

1. Create service with NgxPermissionsService in constructor
<pre>  constructor(
    private permissionsService: NgxPermissionsService
  ) {  }</pre>
  
2. Import NgxPermissionsService
<pre> import { NgxPermissionsService } from 'ngx-permissions';</pre>

3. Create .spec from service, and try run unit test
<pre>  describe("[Service] - PermissionsService", () => {

  let service: PermissionsService;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      providers: [PermissionsService]
    }).compileComponents();

  }); 

  beforeEach(() => {
    service = TestBed.inject(PermissionsService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

});</pre>

## Environment

<pre>
Angular version: 12.0.5
ngx-permissions version: 13.0.1
Jest: 26.0.20
</pre>

**Comment by suspecie** [comment]
Why did you close my issue?
